server:
  port : 8082
spring:
  h2:
    console:
      enabled: true
      path: /database-h2
      settings: 
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:./data/21BlogsData
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
jwt:
  secret: 21blogs
  
service-token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiMTIzNDUiLCJ1c2VyTmFtZSI6Ildvb3R0aXBvbmcgU2Fvd2F5b25nIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTE2MjM5MDIyfQ.-nBxPrEZkYuZcFkZt9Ot-tSp77tc_DMM3rkhxg9VV9M"      
url-create-admin: "/api/createAdmin"
  
message-broker:
   url: "http://localhost:8000/prokeSubscribe"
   url-retrive: "http://localhost:8000/checkingQueueAndRetrive"