INSERT INTO USER (USERID, FULL_NAME, FULL_NAME_EN, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (1, 'ขนิษฐา สมบูรณ์ (แอน)', 'KanitthaS', 'KANITTHA SOMBOON', 'ADMIN', CURRENT_DATE, 'h4RuY22tH64mQhua0oTXj9aOPLLykaUixQuKjEJWWxo=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (2, 'อาภาจรีย์ จั่นยาว (การ์ตูน)', 'ArpajareeJ', 'ARPAJAREE JANYAW', 'ADMIN', CURRENT_DATE, 'xS29XF7xPEcaIJA90LjdIXvO7kyHFcH4W8XXk5fOXkc=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (3, 'มุขสุดา กนกเฉลิมพรรณ (บิว)', 'MooksudaK', 'MOOKSUDA KANOKCHALERMPHAN', 'ADMIN', CURRENT_DATE, 'LIGWPSBbg4mQ8hChi7pZ8QGPLikiWTEDDv1lEKKgODE=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (4, 'กรกนก พันธ์รัมย์ (มายด์)', 'KornkanokP',  'KORNKANOK PHANRUM', 'ADMIN', CURRENT_DATE, 'uroL3TAgHV0E8Meh0n7ybisMgZuW8BUZ51uJAGbZQmk=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (5, 'กุลจิรา เมืองกุดเรือ (เต้ย)', 'KunchiraM', 'KUNCHIRA MUEANGKUTRUEA', 'ADMIN', CURRENT_DATE, 'bplI4wodJgIuK/5w2uKugWR7DGCgmqjoGI037aRRXkA=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (6, 'ปริยวดี คำแหง (ซิน)', 'PiyawadeeK', 'PIYAWADEE KUMHANG', 'ADMIN', CURRENT_DATE, 'JeIhdWV46NLH8doS1haMPYM/vi0z16xYfXZ0yq3KzYs=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (7, 'ปรดา โพธิ์เจริญ (บีบิว)', 'PoradaP', 'PORADA PHOCHAROEN', 'ADMIN', CURRENT_DATE, 'B0aHxT3mvwc+SAXntohjL+MKYBnNi0WNs+M/fwTTWaE=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (8, 'กัลยกร ถุนนอก (นุ่น)', 'KanyakornT', 'KANYAKORN THOONNOK', 'ADMIN', CURRENT_DATE, 'Y8q+7TBs6vSrSgW7IdWMJl4UwUKwqhBphp35Cv+L7cs=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (9, 'วชิราภรณ์ เอี่ยวลับ (เตย)', 'WachirapronA', 'WACHIRAPRON AEUWLUB', 'ADMIN', CURRENT_DATE, 'YwVKeNYJjaRBL3mc5URJV+jL62p1JaAo+ymdAYetEuc=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (10, 'ดวงฤดี เปรมชื่น (นุ๊ก)', 'DuangrudiP', 'DUANGRUDI PREMCHUN', 'ADMIN', CURRENT_DATE, 'wZ+Cs6zj/AptLleo5Xb9UrzGAV43hptoSptGzyvH2FY=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (11, 'ศักรินทร์ จงจริยเลิศ (ปอนด์)', 'SakkarinJ', 'SAKKARIN JONGJARIYALERD', 'ADMIN', CURRENT_DATE, 'DZJxAOixol7p9yw66kUxFLmW0nSMiNzkIrFQzoHKK+g=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (12, 'วรรณี พุทธเกษร (ใหม่)', 'WanneeP', 'WANNEE PUTTAKAYSORN', 'ADMIN', CURRENT_DATE, '+NuLCVPnl/y+puRVHsXIUqlsW0W4yC+ZZxNWjkzpy2w=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (13, 'กุสุมา สุ่มสมิง (กวาง)', 'KusumaS', 'KUSUMA SUMSAMING', 'ADMIN', CURRENT_DATE, '44IKrbb48UQ/xyH4ed/dzu0VOBkdxR5YY0cEoOL1vKI=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (14, 'โสรยา จันทร์เต็มดวง (เดียร์)', 'SorayaJ', 'SORAYA JANTAMDUANG', 'ADMIN', CURRENT_DATE, '1ROHP9m3W8NB6F3mpexcsLpfvVcDUsxnXeOszYcc5mc=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (15, 'ศิญาลี ประเสริฐสังข์ (ดรีม)', 'SiyaleeP', 'SIYALEE PRASERTSANG', 'ADMIN', CURRENT_DATE, 'vl4gvachDbJ1f4ofKsAbvHbrsKEUhM+1dUvaD/ZS91U=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (16, 'พญ. ณัศรัตน์ กุลเกียรติประเสริฐ (หมอน้ำ)', 'NassaratK', 'NASSARAT KULKIATPRASERT', 'REPORT', CURRENT_DATE, 'yGJcFuZHi/gP5G40Ez94FZY12yabkGNuhgzNMZxtZgk=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (17, 'นพ. อนันต์ จึงสุวัฒนานนท์ (หมอหนึ่ง)', 'AnanJ', 'ANAN JUNGSUWATTANANON', 'REPORT', CURRENT_DATE, 'NJiee9NgIjF6yEbbKMSIRNhJkIvB+NzygXqwxOnX0ls=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (18, 'กิติภา สุ่มสมิง (กีต้าร์)', 'KittipaS', 'KITTIPA SUMSAMING', 'REPORT', CURRENT_DATE, '0+pIZHVgF/KVVVQ/sHRlpTDxeOCogGF+Xb6fnhKEoXE=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (19, 'หนึ่งฤทัย งามบุญสวัสดิ์ (หนึ่ง)', 'NuengrutaiN', 'NUENGRUTAI NGAMBOONSAWAT', 'REPORT', CURRENT_DATE, 'n/0oPDvA72mCwGctueXoIH5av5dggdQRSk1rldXk0xk=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (20, 'ชัยฤกษ์ งามบุญสวัสดิ์ (เจมส์)', 'ChairuekN', 'CHAIRUEK NGAMBOONSAWAT', 'REPORT', CURRENT_DATE, 'kJokhr7Dv482JRk4csWsHQiDSf5y48tD4Y1fuUFAMSI=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (21, 'ผู้ดูแลระบบ', 'AdminBS', 'ADMIN BUSTLESOFT', 'ADMIN', CURRENT_DATE, '4eYjIAnU3leRb1856GWPSGWVlx4XdxLOZG2Ft060/qA=');
INSERT INTO USER (USERID, FULL_NAME, USERNAME, ROLE_NAME, LAST_MODIFIED_DATE, PASSWORD) 
VALUES (22, 'ผู้ดูละระบบ', 'ReportBS', 'REPORT BUSTLESOFT', 'REPORT', CURRENT_DATE, '4eYjIAnU3leRb1856GWPSGWVlx4XdxLOZG2Ft060/qA=');
