server:
  port : 8000
spring:
  h2:
    console:
      enabled: true
      path: /database-h2
      settings: 
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:./data/21BlogsData
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

service-token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiMTIzNDUiLCJ1c2VyTmFtZSI6Ildvb3R0aXBvbmcgU2Fvd2F5b25nIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNTE2MjM5MDIyfQ.-nBxPrEZkYuZcFkZt9Ot-tSp77tc_DMM3rkhxg9VV9M"      

sync-events: create-customer
      
msg: 
  service:
    customer-service-event-receiver: "http://localhost:8081/api/event-receiver"
    admin-service-event-receiver: "http://localhost:8082/api/event-receiver"
    authenticate-service-event-receiver: "http://localhost:8083/api/event-receiver"
    report-service-event-receiver: "http://localhost:8084/api/event-receiver"

  